config/routes.rb
Rails.application.routes.draw do
  get '/', to: "devices#create"
  get '/show', to: "devices#show", as: :device

  get "/login",     to: "sessions#new"
  post "/login",    to: "sessions#create"

  namespace :api, defaults: { format: :json }  do
    namespace :v1 do
      resources :signage, only: [:index, :update]
      resources :slides, onyl: [:show, :create, :update]
    end
  end

  namespace :admin do
    get '/update_slides', to: "slides#refresh", as: :refresh_slides
    resources :slides, only: [:index, :destroy, :new, :edit]
    resources :devices, only: [:index, :edit, :update, :destroy] do
      collection do
        post :reveal
      end
    end
    resources :display, only: [:update]
  end
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  def self.display_custom_on_rotation(counter)
    custom_slides = Slide.where('custom = ? AND active = ?', true, true)
    if custom_slides.pluck(:display_rate).include?(counter)
      return custom_slides.where('display_rate = ?', counter).order('RANDOM()').first
    end
  end

  def update_information(params)
    params[:display_rate] = params[:display_rate].to_i
    self.update(params)
    self.update(role: "confirm#{determine_role}")
  end

  def confirm_save
    self.role = "confirm#{determine_role}"
    self.custom = true
    self.display_rate = self.display_rate.to_i
    self.save
  end

  def determine_role
    if !title.empty? && subtitle.empty?
      '-lg-text'
    elsif !title.empty? && !subtitle.empty?
      '-lg-sub-text'
    elsif title.empty? && !subtitle.empty?
      '-sub-text'
    else
      '-custom-image'
    end
  end

  def custom_background?
    self.custom_background != 'https://static1.squarespace.com/static/5602b79ee4b0a65d125ea3c4/t/57b37b0bb3db2b80ee031840/1471380241780/DSC05223.jpeg'
  end

  def self.update_slides
    slides = fetch_slides
    delete_slides
    insert_slides(slides)
  end

  def custom_style
    role.split('-')[1..3].join(' ').capitalize
  end

  def self.update_counter(counter)
    return 1 if counter >= Slide.where('custom = ? AND active = ?', true, true).pluck(:display_rate).sort.last.to_i
    counter += 1
  end

  private
    def self.delete_slides
      slides = Slide.where.not(custom: true)
      slides.destroy_all
    end

    def self.fetch_slides
      roles = fetch_roles
      roles.map do |role|
        TreloraServices.new.house_listing(role)
      end.flatten
    end

    def self.fetch_roles
      TreloraServices.new.get_roles
    end

    def self.translate_role(x)
      x.gsub(' ', '').downcase
    end

    def self.insert_slides(slides)
      slides.each do |slide|
        Slide.create(role: slide[:signage_role],
                     api_role: self.translate_role(slide[:signage_role]),
                     ribbon: slide[:signage_ribbon],
                     ribbon_color: slide[:signage_ribbon_color],
                     title: slide[:signage_title],
                     subtitle: slide[:signage_subtitle],
                     best_large_image: slide[:best_large_image]
        )
      end
    end
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < ApplicationController
  layout "admin"
  before_action :authorize!

  def refresh
    Slide.update_slides
    Role.update_roles
    redirect_to admin_devices_path
  end

  def index
    @custom_slides = Slide.where(custom: true).order(:created_at)
  end

  def new
  end

  def edit
    @slide = Slide.find_by(id: params[:id])
  end

  def destroy
    slide = Slide.find(params[:id])
    slide.destroy
    flash[:success] = 'Custom Slide Successfully Deleted'
    redirect_to admin_slides_path
  end

  private
  def slide_params
    params.require(:slide).permit(
      :title,
      :subtitle,
      :display_rate,
      :active,
      :ribbon_display,
      :ribbon,
      :ribbon_color,
      :custom_background
    )
  end

  def confirm_update(params)
    slide = Slide.find(params[:id])
    if slide.update_preview?
      slide.confirm_save
    else
      params = slide_params
      params.merge!(role: "confirm#{slide.determine_role}")
      slide.update(params)
    end
  end
end

app/controllers/api/v1/slides_controller.rb
module Api
  module V1
    class SlidesController < ApiController
      respond_to :json

      def show
        slide = Slide.find_by(id: params[:id])
        render json: slide
      end

      def create
        slide = Slide.new(slide_params)
        if slide.confirm_save
          render json: {'redirect': true,
                        'redirect_url': admin_slides_path}
        else
          render json: {'redirect': false,
                        'error': 'slide did not save'}
        end
      end

      def update
        slide = Slide.find_by(id: params[:id])
        if slide.update_information(slide_params)
          render json: {'redirect': true,
                        'redirect_url': admin_slides_path}
        else
          render json: {'redirect': false,
                        'error': 'slide did not save'}
        end
      end

      private
      def slide_params
        params.require(:slide).permit(
          :title,
          :subtitle,
          :ribbon_display,
          :ribbon,
          :ribbon_color,
          :custom_background,
          :display_rate,
          :active
        )
      end
    end
  end
end

app/views/admin/slides/_trelora_logo.html.erb
<div class="text-center">
  <a href="<%= admin_devices_path %>"><%= image_tag "trelora_logo.png", id: "trelora-logo" %></a>
</div>

app/views/admin/slides/edit.html.erb
<%= render partial: 'trelora_logo' %>

<h1 class="text-center" id="titles">Edit Slide ID <%= @slide.id %></h1>

<center>
<%= react_component 'Main', { slideId: @slide.id } %>
</center>

app/views/admin/slides/index.html.erb
<%= render partial: 'trelora_logo' %>

<h1 class="text-center" id="titles">All Custom Slides</h1>

<center>
  <div class="text-center">
    <%= button_to "Create Custom Slide", new_admin_slide_path, class: 'font-format button', id: "button-refresh", method: :get %>
  </div>
  <table class="table" id='slide-index'>
    <tr>
      <th>Slide ID</th>
      <th>Title/ Subtitle</th>
      <th>Style</th>
      <th>Display Rate</th>
      <th>Ribbon Display?</th>
      <th>Custom Background?</th>
      <th>Active In Rotation?</th>
      <th>Update Slide</th>
    </tr>
    <% @custom_slides.each do |slide| %>
      <tr data-id='<%= slide.id %>' id='slide-<%= slide.id %>'>
        <td><%= link_to slide.id, edit_admin_slide_path(slide.id) %></td>
        <td><strong>Title: </strong><%= slide.title.empty? ? 'N/A' : slide.title %><br><strong>Subtitle: </strong><%= slide.subtitle.empty? ? 'N/A' : slide.subtitle %></td>
        <td><%= slide.custom_style %></td>
        <td><%= slide.display_rate == 0 ? 'Random' : "#{slide.display_rate} Frames" %></td>
        <td><%= check_box_tag 'ribbon_display', '1', (slide.ribbon_display ? true : false), class: 'active' %></td>
        <td><%= slide.custom_background? ? 'Yes' : 'No' %></td>
        <td><%= check_box_tag 'active', '1', (slide.active ? true : false), class: 'active' %></td>
        <td><%= link_to 'Edit', edit_admin_slide_path(slide.id) %><br><%= link_to 'Delete', admin_slide_path(slide.id), method: :delete, data: {confirm: 'Are you sure you want to permanently delete this slide?'} %></td>
      </tr>
    <% end %>
  </table>
</center>

app/views/admin/slides/new.html.erb
<%= render partial: 'trelora_logo' %>

<h1 class="text-center" id="titles">Create Custom Slide</h1>

<center>
<%= react_component 'Main' %>
</center>