config/routes.rb
Rails.application.routes.draw do
  get '/', to: "devices#create"
  get '/show', to: "devices#show", as: :device

  get "/login",     to: "sessions#new"
  post "/login",    to: "sessions#create"

  namespace :api, defaults: { format: :json }  do
    namespace :v1 do
      resources :signage, only: [:index, :update]
      resources :slides, onyl: [:show, :create, :update]
    end
  end

  namespace :admin do
    get '/update_slides', to: "slides#refresh", as: :refresh_slides
    resources :slides, only: [:index, :destroy, :new, :edit]
    resources :devices, only: [:index, :edit, :update, :destroy] do
      collection do
        post :reveal
      end
    end
    resources :display, only: [:update]
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  validates :device_code, uniqueness: true

  before_save :set_default_role

  def set_default_role
    if self.role.blank?
      self.role = (Role.find_by(role: "sold") || Role.last).role
    end
  end

  def seen!
    self.update(last_visit: Time.now.to_s)
  end

  def generate_device_code
    while true
      code = SecureRandom.hex(2)
      break if update(device_code: code)
    end
    device_code
  end
end

app/controllers/admin/devices_controller.rb
class Admin::DevicesController < ApplicationController
  layout "admin"
  before_action :authorize!

  def index
    @devices = AdminPresenter.new
    @active_custom_slides = Slide.where(custom: true, active: true)
  end

  def edit
    @device = Device.find_by(id: params[:id])
  end

  def update
    device = Device.find(params[:id])
    if device.update(device_params)
      redirect_to admin_devices_path
    else
      render edit_admin_device_path(params[:id])
    end
  end

  def destroy
    Device.find(params[:id]).delete
    redirect_to admin_devices_path
  end

  def reveal
    Display.last.update_column(:show_device_codes, !Display.last.show_device_codes)
    redirect_to admin_devices_path
  end

  private
  def device_params
    params.require(:device).permit(:device_code, :nickname, :role)
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def create
    if cookies[:device_code].nil? || Device.find_by(device_code: cookies[:device_code]).blank?
      device = create_device
    end
    redirect_to device_path(0)
  end

  def show
    @device = Device.find_by(device_code: cookies[:device_code])
    if @device.present?
      @device.seen!
    else
      @device = create_device
    end
  end
end

app/views/admin/devices/edit.html.erb
<div class="text-center">
  <h1 id="titles">Edit Device</h1>
  <%= form_for [:admin, @device] do |f| %>
      <%= f.label :device_code, class: 'font-format' %>
      <div class="form-group">
        <%= f.text_field :device_code, class: 'form-control' %>
      </div>

      <%= f.label :nickname, class: 'font-format' %>
      <div class="form-group">
        <%= f.text_field :nickname, class: 'form-control' %>
      </div>

      <%= f.label :role, class: 'font-format' %>
      <div class="form-group">
        <%= f.select(:role, options_for_select(Role.all_roles), {}, {class: "form-control"}) %>
      </div>

      <div class="form-group ">
        <%= f.submit "Submit", class: 'font-format', id: 'button-submit' %>
      </div>
  <% end %>
</div>

app/views/admin/devices/index.html.erb
  <div class="text-center">
    <%= image_tag "trelora_logo.png", id: "trelora-logo" %>
  </div>

  <h1 class="text-center" id="titles">Devices</h1>

  <p id="refresh">
    Refresh: Use button below to refresh or setup the slides and roles from the Trelora Signage API.
  </p>

  <div class="text-center">
    <%= button_to "Refresh", admin_refresh_slides_path, class: 'font-format button', id: "button-refresh", method: :get %>
  </div>

<p id="custom">
  Custom Slides: Use the buttons below to create a slide or see all slides to edit and/or delete.<br />
  Custom Slides Currently in Active Rotation: <%= link_to @active_custom_slides.count, admin_slides_path %>
</p>

<center>
  <table id="preview-options">
    <tr>
      <td style="padding: 0 30px 50px 80px;"><%= button_to "Create Custom Slide", new_admin_slide_path, class: 'font-format button', id: "button-refresh", method: :get %></td>
      <td style="padding: 0 30px 50px 80px;"><%= button_to "See All Custom Slides", admin_slides_path, class: 'font-format button', id: "button-refresh", method: :get %></td>
    </tr>
  </table>
</center>

  <p id="timer">
    <i class="fa fa-clock-o" aria-hidden="true"></i>  Current Slide Time: <%= @devices.time %> second(s) per slide
  </p>

  <%= form_for([:admin, @devices.display]) do |f| %>
    <div class="form-group text-center">
      <%= f.label :time, class: 'font-format' %>
      <%= f.text_field :time, class: 'form-control' %>
      <%= f.submit "Submit", class: 'font-format button', id: 'button-submit' %>
    </div>
  <% end %>

  <br />
  <hr />
  <br />


  <div class="text-center">
    <% if Display.last.show_device_codes %>
      <p>
        The device codes ARE currently being shown on the slides!
      </p>
      <%= button_to "Hide Codes on Devices", reveal_admin_devices_path, class: 'font-format button', id: "button-unreveal" %>
    <% else %>
      <p>
        The device codes are NOT currently being shown.
      </p>
      <%= button_to "Reveal Codes on Devices", reveal_admin_devices_path, class: 'font-format button', id: "button-reveal" %>
    <% end %>
  </div>


  <div class="text-center" id="tv-icon">
    <i class="fa fa-television" aria-hidden="true"></i>
  </div>

  <table class="table" id="admin-table">
    <tr>
      <th>ID</th>
      <th>Code</th>
      <th>Nickname</th>
      <th>Role</th>
      <th>Last Visited</th>
      <th>Delete Device</th>
    </tr>
    <% @devices.all.each do |device| %>
      <tr>
        <td><%= link_to device.id, edit_admin_device_path(device.id) %></td>
        <td><%= device.device_code %></td>
        <td><%= device.nickname %></td>
        <td><%= device.role %></td>
        <td><%= formatted_time(device.last_visit) %></td>
        <td><%= link_to "Delete", admin_device_path(device.id), method: :delete %></td>
      </tr>
    <% end %>
  </table>